# Generated by Django 5.0.2 on 2024-03-03 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_output'),
    ]

    operations = [
        migrations.AddField(
            model_name='output',
            name='bigop',
            field=models.TextField(default=''),
        ),
    ]
