# Generated by Django 5.0.2 on 2024-03-04 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_ipaddress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='output',
            name='bigop',
        ),
    ]
